" Specify a directory for plugins
" - For Neovim: ~/.local/share/nvim/plugged
" - Avoid using standard Vim directory names like 'plugin'
call plug#begin('~/.vim/plugged')

" Make sure you use single quotes

Plug 'altercation/vim-colors-solarized'
Plug 'vim-airline/vim-airline'
Plug 'vim-airline/vim-airline-themes'
Plug 'scrooloose/nerdtree'
Plug 'GEverding/vim-hocon'
Plug 'ctrlpvim/ctrlp.vim'

" Initialize plugin system
call plug#end()

" colorscheme solarized
syntax enable
set background=dark
colorscheme solarized

" Tabulation and indentation
set expandtab
set shiftwidth=4
set softtabstop=4

set autoindent

" Diplay line numbers
set nu

" autocompletion settings
set wildmenu
set wildmode=list:longest,full

" Show buffer line at top with buffer number with Airline.
let g:airline#extensions#tabline#enabled = 1
let g:airline#extensions#tabline#buffer_nr_show = 1

" NERDTree
let g:NERDTreeWinSize=50
"" Ctrl-N focus on NerdTree
nmap <silent> <C-n> :call g:NERDTreeFocus()<CR>

""
" Automatically append closing characters
" http://vim.wikia.com/wiki/Automatically_append_closing_characters
"

inoremap {<CR>  {<CR>}<Esc>O
inoremap [<CR> [<CR>]<C-o>O

"
""
