" Specify a directory for plugins
" - For Neovim: ~/.local/share/nvim/plugged
" - Avoid using standard Vim directory names like 'plugin'
call plug#begin('~/.vim/plugged')

" Make sure you use single quotes

Plug 'altercation/vim-colors-solarized'
Plug 'vim-airline/vim-airline'
Plug 'vim-airline/vim-airline-themes'
Plug 'scrooloose/nerdtree'
Plug 'GEverding/vim-hocon'
Plug 'ctrlpvim/ctrlp.vim'
Plug 'tpope/vim-ragtag'
Plug 'mfukar/robotframework-vim'
"Plug 'Vimjas/vim-python-pep8-indent'
Plug 'python-mode/python-mode', { 'for': 'python', 'branch': 'develop' }
Plug 'glench/vim-jinja2-syntax'
Plug 'christoomey/vim-tmux-navigator'
Plug 'ryanoasis/vim-devicons'
Plug 'rbgrouleff/bclose.vim'

" Initialize plugin system
call plug#end()

syntax enable

" colorscheme solarized
let g:solarized_termcolors=256
set background=dark
colorscheme solarized

" Tabulation and indentation
set expandtab
set shiftwidth=4
set softtabstop=4

set autoindent

" Diplay line numbers
set nu

" autocompletion settings
set wildmenu
set wildmode=list:longest,full

" Show buffer line at top with buffer number with Airline.
let g:airline#extensions#tabline#enabled = 1
let g:airline#extensions#tabline#buffer_nr_show = 1

" NERDTree
let g:NERDTreeWinSize=50
"" Ctrl-N focus on NerdTree
nmap <silent> <C-n> :call g:NERDTreeFocus()<CR>

""
" Automatically append closing characters
" http://vim.wikia.com/wiki/Automatically_append_closing_characters
"

inoremap {<CR>  {<CR>}<Esc>O
inoremap [<CR> [<CR>]<C-o>O

"
""

set pastetoggle=<F2>

""
" Quick change window keys
if exists('$TMUX')
  function! TmuxOrSplitSwitch(wincmd, tmuxdir)
    let previous_winnr = winnr()
    silent! execute "wincmd " . a:wincmd
    if previous_winnr == winnr()
      call system("tmux select-pane -" . a:tmuxdir)
      redraw!
    endif
  endfunction

  let previous_title = substitute(system("tmux display-message -p '#{pane_title}'"), '\n', '', '')
  let &t_ti = "\<Esc>]2;vim\<Esc>\\" . &t_ti
  let &t_te = "\<Esc>]2;". previous_title . "\<Esc>\\" . &t_te

  nnoremap <silent> <C-h> :call TmuxOrSplitSwitch('h', 'L')<cr>
  nnoremap <silent> <C-j> :call TmuxOrSplitSwitch('j', 'D')<cr>
  nnoremap <silent> <C-k> :call TmuxOrSplitSwitch('k', 'U')<cr>
  nnoremap <silent> <C-l> :call TmuxOrSplitSwitch('l', 'R')<cr>
else
  map <C-h> <C-w>h
  map <C-j> <C-w>j
  map <C-k> <C-w>k
  map <C-l> <C-w>l
endif

" Python Mode
" let g:pymode = 0
" let g:pymode_lint = 1
" let g:pymode_lint_on_write = 1
let g:pymode_lint_cwindow = 0
