#!/usr/bin/env bash
#
# inspired from https://github.com/holman/dotfiles

source $HOME/.dotfiles/script/utils

log_file=$HOME/.dotfiles/install.log

install_dependencies () {
  sudo apt-get -y install build-essential linux-headers-$(uname -r) git vim screen
}

install_submodules () {
  cd $HOME/.dotfiles
  git submodule init
  git submodule update
}

install_dotfiles () {
  for file in $(ls ~/.dotfiles/dotfiles)
  do
    install_dotfile $file
  done
}

install_dotfile () {
  file=$1
  src=$HOME/.dotfiles/dotfiles/$file
  dst=$HOME/.$file

  if [ -f $dst ] || [ -d $dst ]
  then
    if [ -h $dst ] && [ $(readlink $dst) == $src ]
    then
      info "$dst is already symlinked"
    else
      while $loop
      do
        loop=false

        user "File already exists: `basename $file`, what do you want to do? show [d]ifferences, [s]kip, [o]verwrite, [b]ackup?"
        read action

        # erase previous line
        echo -en "\e[1A\e[K"

        case "$action" in
          d )
            diff $dst $src | less
            loop=true
            ;;
          o )
            rm -rf "$dst"
            success "removed $dst"
            link_files $src $dst
            ;;
          b )
            mv "$dst" "${dst}.backup"
            success "moved $dst to ${dst}.backup"
            link_files $src $dst
            ;;
          * )
            ;;
        esac
      done
    fi
  else
    link_files $src $dst
  fi
}

install_powerline_fonts () {
  fc-cache -vf ~/.fonts
}

install_solarized_for_gnome_terminal () {
  bash ~/.dotfiles/script/gnome-terminal-colors-solarized/set_dark.sh
}

install_task () {
  task=$1
  title=$2

  process "$title"
  $task > $log_file
  success "$title"
}

install_task install_dependencies "install dependencies"
install_task install_submodules "install submodules"
install_dotfiles
install_task "install_powerline_fonts" "install powerline fonts"
install_task install_solarized_for_gnome_terminal "install solarized"
