#!/usr/bin/env bash

install_rbenv () {
  if ! [ -d ~/.rbenv ]; then
    git clone https://github.com/sstephenson/rbenv.git ~/.rbenv

    echo "# rbenv\n\n" >> ~/.bashrc
    echo 'export PATH="$HOME/.rbenv/bin:$PATH"' >> ~/.bashrc
    echo 'eval "$(rbenv init -)"' >> ~/.bashrc

    source ~/.bashrc
  fi
}

install_ruby_build () {
  if ! [ -d ~/.rbenv/plugins/ruby-build ]; then
    git clone https://github.com/sstephenson/ruby-build.git ~/.rbenv/plugins/ruby-build

    # Suggested build environment
    # https://github.com/sstephenson/ruby-build/wiki
    sudo apt-get install autoconf bison build-essential libssl-dev libyaml-dev libreadline6 libreadline6-dev zlib1g zlib1g-dev
  fi
}

install_rbenv
install_ruby_build
